services:
  vault66-app:
    container_name: vault66
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run dev
